/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.signuppage;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vsabale
 */
public class admission extends javax.swing.JFrame {

    private static void reload() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form admission
     */
    public admission() {
        initComponents();
        displaycashfirst();
        fill_combo_box();
      int r=getRNo();
     r++;
      txt_reciept_no.setText(Integer.toString(r));
       
        
    }
   
    public void displaycashfirst()
    {
        lbl_upid.setVisible(false);
        txt_upid.setVisible(false);
        lbl_check_no.setVisible(false);
        txt_check_no.setVisible(false);
        lbl_bank_name.setVisible(false);
        txt_bank_name.setVisible(false);
    }
    
    boolean validation()
    {
          if (txt_receiver_name.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter the Receiver Name first.");
            return false;
        }
        if (date.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Enter today's date.");
            return false;
        }
        if (txt_amount.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter the Amount (in numbers).");
            return false;
        }
        String paymentMode = combo_mode_payment.getSelectedItem().toString();
        if (paymentMode.equalsIgnoreCase("check")) {
            if (txt_check_no.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Enter the Check Number.");
                return false;
            }
            if (txt_bank_name.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Enter the Bank Name.");
                return false;
            }
        }
        if (paymentMode.equalsIgnoreCase("PhonePe")) {
            if (txt_upid.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Enter the UPID.");
                return false;
            }
        }
        return true;        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_update_coure = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_course_list1 = new javax.swing.JButton();
        btn_home1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_upid = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        lbl_gst = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gst = new javax.swing.JLabel();
        lbl_bank_name = new javax.swing.JLabel();
        lbl_check_no = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combo_mode_payment = new javax.swing.JComboBox<>();
        txt_upid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_bank_name = new javax.swing.JTextField();
        txt_reciept_no = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        combo_mode_course = new javax.swing.JComboBox<>();
        txt_check_no = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_total_in_word = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_receiver_name = new javax.swing.JTextField();
        txt_cgst = new javax.swing.JTextField();
        txt_sgst = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_head = new javax.swing.JTextField();
        btn_print = new javax.swing.JButton();
        txt_amount = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_note = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setBackground(new java.awt.Color(255, 255, 204));
        btn_logout.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 0, 51));
        btn_logout.setText("LOGOUT");
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 270, 50));

        btn_add.setBackground(new java.awt.Color(255, 255, 204));
        btn_add.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btn_add.setForeground(new java.awt.Color(0, 0, 255));
        btn_add.setText("ADD COURSE");
        btn_add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 270, 50));

        btn_update_coure.setBackground(new java.awt.Color(255, 255, 204));
        btn_update_coure.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btn_update_coure.setText("UPDATE COURSE");
        btn_update_coure.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_update_coure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_coureActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update_coure, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 270, 50));

        btn_delete.setBackground(new java.awt.Color(255, 255, 204));
        btn_delete.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(51, 51, 255));
        btn_delete.setText("DELETE COURSE");
        btn_delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 270, 50));

        btn_course_list1.setBackground(new java.awt.Color(255, 255, 204));
        btn_course_list1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btn_course_list1.setText("COURSE LIST");
        btn_course_list1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        btn_course_list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_course_list1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_course_list1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 270, 50));

        btn_home1.setBackground(new java.awt.Color(255, 255, 204));
        btn_home1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btn_home1.setText("HOME");
        btn_home1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btn_home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 270, 50));

        jButton1.setText("CLEAR");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 590));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_upid.setForeground(new java.awt.Color(255, 0, 51));
        lbl_upid.setText("upid");
        jPanel3.add(lbl_upid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 102, -1));

        date.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 185, 28));

        lbl_gst.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_gst.setForeground(new java.awt.Color(0, 204, 102));
        lbl_gst.setText("ABc231U");
        jPanel3.add(lbl_gst, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 82, 24));

        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Date");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 32, 82, -1));

        gst.setForeground(new java.awt.Color(255, 102, 102));
        gst.setText("GST");
        jPanel3.add(gst, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 82, 24));

        lbl_bank_name.setForeground(new java.awt.Color(255, 0, 51));
        lbl_bank_name.setText("Bank Name");
        jPanel3.add(lbl_bank_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 102, -1));

        lbl_check_no.setForeground(new java.awt.Color(255, 0, 51));
        lbl_check_no.setText("check no.");
        jPanel3.add(lbl_check_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 102, -1));

        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("Mode of Payment");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 102, -1));

        combo_mode_payment.setBackground(new java.awt.Color(204, 255, 204));
        combo_mode_payment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combo_mode_payment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Phone Pe", "Check No" }));
        combo_mode_payment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        combo_mode_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_mode_paymentActionPerformed(evt);
            }
        });
        jPanel3.add(combo_mode_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 180, -1));

        txt_upid.setBackground(new java.awt.Color(204, 255, 204));
        txt_upid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_upid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_upid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, 20));

        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("Reciept No");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 22, 82, -1));

        txt_bank_name.setBackground(new java.awt.Color(255, 255, 153));
        txt_bank_name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(txt_bank_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 180, -1));

        txt_reciept_no.setBackground(new java.awt.Color(153, 255, 153));
        txt_reciept_no.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(txt_reciept_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 180, -1));

        jLabel17.setForeground(new java.awt.Color(0, 0, 204));
        jLabel17.setText("Course");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 102, -1));

        combo_mode_course.setBackground(new java.awt.Color(204, 255, 204));
        combo_mode_course.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));
        combo_mode_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_mode_courseActionPerformed(evt);
            }
        });
        jPanel3.add(combo_mode_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 180, -1));

        txt_check_no.setBackground(new java.awt.Color(204, 255, 204));
        txt_check_no.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_check_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_check_noActionPerformed(evt);
            }
        });
        jPanel3.add(txt_check_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, -1));

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 51, 0));
        jSeparator2.setForeground(new java.awt.Color(204, 0, 51));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 750, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 51, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 150, 10));

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("CGST %7");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 82, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Student Name");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 82, -1));

        txt_total_in_word.setBackground(new java.awt.Color(204, 255, 204));
        txt_total_in_word.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_total_in_word.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(txt_total_in_word, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 370, -1));

        txt_total.setBackground(new java.awt.Color(255, 204, 255));
        txt_total.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 130, -1));

        txt_receiver_name.setBackground(new java.awt.Color(204, 255, 204));
        txt_receiver_name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_receiver_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(txt_receiver_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 220, -1));

        txt_cgst.setBackground(new java.awt.Color(204, 204, 255));
        txt_cgst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel4.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 130, -1));

        txt_sgst.setBackground(new java.awt.Color(204, 204, 255));
        txt_sgst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel4.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 130, -1));

        jSeparator4.setBackground(new java.awt.Color(255, 51, 0));
        jSeparator4.setForeground(new java.awt.Color(204, 0, 51));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 750, 10));

        jLabel11.setText("Amount");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 82, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 2, 12)); // NOI18N
        jLabel12.setText("Signature");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 82, -1));

        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("SGST  %7");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 82, -1));

        jLabel14.setText("Note :");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 82, -1));

        txt_head.setBackground(new java.awt.Color(204, 255, 255));
        txt_head.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_head.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(txt_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, -1));

        btn_print.setBackground(new java.awt.Color(255, 204, 153));
        btn_print.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_print.setText("PRINT");
        btn_print.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        jPanel4.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 70, -1));

        txt_amount.setBackground(new java.awt.Color(204, 204, 255));
        txt_amount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amountActionPerformed(evt);
            }
        });
        jPanel4.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 180, -1));

        jLabel15.setText("Head");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 82, -1));

        jSeparator5.setBackground(new java.awt.Color(255, 51, 0));
        jSeparator5.setForeground(new java.awt.Color(204, 0, 51));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 150, 10));

        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Total in word");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 82, -1));

        txt_note.setBackground(new java.awt.Color(204, 255, 255));
        txt_note.setColumns(20);
        txt_note.setRows(5);
        txt_note.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setViewportView(txt_note);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 370, 320, 50));

        jLabel18.setText("Total");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 82, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 810, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_mode_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_mode_paymentActionPerformed
        

          if (combo_mode_payment.getSelectedIndex() == 0) {
            lbl_check_no.setVisible(false);
            txt_check_no.setVisible(false);
            lbl_bank_name.setVisible(false);
            txt_bank_name.setVisible(false);

        }
        if (combo_mode_payment.getSelectedIndex() == 1) {
            lbl_check_no.setVisible(false);
            txt_check_no.setVisible(false);
            lbl_bank_name.setVisible(false);
            txt_bank_name.setVisible(false);
            txt_upid.setVisible(true);
            lbl_upid.setVisible(true);

        }
        if (combo_mode_payment.getSelectedIndex() == 2) {
            lbl_check_no.setVisible(true);
            txt_check_no.setVisible(true);
            lbl_bank_name.setVisible(true);
            txt_bank_name.setVisible(true);
            lbl_gst.setVisible(true);
            txt_upid.setVisible(false);
            lbl_upid.setVisible(false);
        }
       


        // TODO add your handling code here:
    }//GEN-LAST:event_combo_mode_paymentActionPerformed
    
    public void clearFields() {
    // Clear text fields
    txt_reciept_no.setText("");
    txt_receiver_name.setText("");
    txt_check_no.setText("");
    txt_bank_name.setText("");
    txt_amount.setText("");
    txt_cgst.setText("");
    txt_sgst.setText("");
    txt_total_in_word.setText("");
    txt_note.setText("");

    // Reset combo boxes to their default item (e.g., first item or null)
    combo_mode_payment.setSelectedIndex(0); // Assuming 0 is the default
    combo_mode_course.setSelectedIndex(0); // Assuming 0 is the default

    // Reset labels
    lbl_gst.setText("");

    // Optionally, reset focus to the first field
    txt_reciept_no.requestFocus();
}

 
    public String insertData()
    {
        String status = null;
       int rece_no=Integer.parseInt(txt_reciept_no.getText());
       String student_name=txt_receiver_name.getText();
       String payment=combo_mode_payment.getSelectedItem().toString();
       String check=txt_check_no.getText();
       String bank_name=txt_bank_name.getText();
       String coursename=combo_mode_course.getSelectedItem().toString();
       String gstin=lbl_gst.getText();
        float total=Float.parseFloat(txt_amount.getText());
       
        float cgst=Float.parseFloat(txt_cgst.getText());
         float sgst=Float.parseFloat(txt_sgst.getText());
       String total_word=txt_total_in_word.getText();  
       String note=txt_note.getText();
        
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/csfsms", "root", "1111");
    String sql = "INSERT INTO fess_details VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?)";
    PreparedStatement st = con.prepareStatement(sql);

    st.setInt(1, rece_no);
    st.setString(2, student_name);
    st.setString(3, payment);
    st.setString(4, check);
    st.setString(5, bank_name);
    st.setString(6, coursename);
    st.setString(7, gstin);
    st.setFloat(8, total);
    st.setFloat(9, cgst);
    st.setFloat(10, sgst);
    st.setString(11, total_word);
    st.setString(12,note);
    int i = st.executeUpdate();
    if (i > 0) {
        JOptionPane.showMessageDialog(this, "Record inserted successfully");
         JOptionPane.showMessageDialog(this, "YOUR ADDMISION IS SUCCESSFULLY COMPLATE !!");
    } else {
        JOptionPane.showMessageDialog(this, "Record insertion failed");
    }
} catch (SQLException e) {
    if (e.getMessage().contains("doesn't exist")) {
        JOptionPane.showMessageDialog(this, "Table 'fess_details' does not exist in the database. Please verify!");
    }
    e.printStackTrace();
} catch (Exception e) {
    e.printStackTrace();
}
        return null;

    }
     
    public int getRNo() {
    int rno = 0;
    try {
        // Load the MySQL driver
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Establish the database connection
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/csfsms?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "1111");

        // SQL query to get the max receipt number
        String sql = "SELECT MAX(rece_no) AS max_rece_no FROM fess_details";
        PreparedStatement st = con.prepareStatement(sql);
        ResultSet rs = st.executeQuery();

        // Get the result
        if (rs.next()) {
            rno = rs.getInt(1); // Fetch the value by index
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Please verify your database connection or table structure!", "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    return rno;
}

    
    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
      
    validation();
   
       insertData();
        try {
            sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(admission.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btn_printActionPerformed

    private void txt_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amountActionPerformed

        String s1=txt_amount.getText();
         float amt=Float.parseFloat(s1);
         
         float cgst=amt*0.07f;
          float sgst=amt*0.07f;
          txt_cgst.setText(Float.toString(cgst));
          txt_sgst.setText(Float.toString(sgst));
          float t=amt+cgst+sgst;
          txt_total.setText(Float.toString(t));
          txt_total_in_word.setText(NumberToWordsConverter.convert((int)t));
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_txt_amountActionPerformed

    private void combo_mode_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_mode_courseActionPerformed
  String s1 = combo_mode_course.getSelectedItem().toString();
            txt_head.setText(s1);        
            
    }//GEN-LAST:event_combo_mode_courseActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed

        
        DeleteCourse DeleteCourse= new DeleteCourse(); 
        DeleteCourse.setVisible(true);



        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_update_coureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_coureActionPerformed
 UpdateCourse UpdateCourse = new UpdateCourse();
 UpdateCourse.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_update_coureActionPerformed

    private void btn_course_list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_course_list1ActionPerformed
        coursedetails courseDetails = new coursedetails();
            courseDetails.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_course_list1ActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
      AddCourse  AddCourse=new AddCourse();
            AddCourse.setVisible(true);
            
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


clearFields();

        






        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_check_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_check_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_check_noActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

clearFields();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
clearFields();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
clearFields();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    
    public void fill_combo_box() {
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/csfsms?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "1111");
            String sql = "select cname,cost from course";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                combo_mode_course.addItem(rs.getString("cname"));
                combo_mode_course.addItem(rs.getString("cost"));
            }
          
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public class NumberToWordsConverter {

        public static final String[] units = {"", "One", "Two", "Three", "Four",
            "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Eleven", "Twelve",
            "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen",
            "Eighteen", "Nineteen"};

        public static final String[] tens = {
            "", // 0
            "", // 1
            "Twenty", // 2
            "Thirty", // 3
            "Forty", // 4
            "Fifty", // 5
            "Sixty", // 6
            "Seventy", // 7
            "Eighty", // 8
            "Ninety" // 9
        };

        public static String convert(final int n) {
            if (n < 0) {
                return "Minus " + convert(-n);
            }

            if (n < 20) {
                return units[n];
            }

            if (n < 100) {
                return tens[n / 10] + ((n % 10 != 0) ? " " : "") + units[n % 10];
            }

            if (n < 1000) {
                return units[n / 100] + " Hundred" + ((n % 100 != 0) ? " " : "") + convert(n % 100);
            }

            if (n < 100000) {
                return convert(n / 1000) + " Thousand" + ((n % 10000 != 0) ? " " : "") + convert(n % 1000);
            }

            if (n < 10000000) {
                return convert(n / 100000) + " Lakh" + ((n % 100000 != 0) ? " " : "") + convert(n % 100000);
            }

            return convert(n / 10000000) + " Crore" + ((n % 10000000 != 0) ? " " : "") + convert(n % 10000000);
        }

        public static void main(final String[] args) {
            Scanner sc = new Scanner(System.in);
            System.out.println("Enter the Amount : ");
            int n = sc.nextInt();

            System.out.println(convert(n) + " Only");

        }
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_course_list1;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_home1;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_update_coure;
    private javax.swing.JComboBox<String> combo_mode_course;
    private javax.swing.JComboBox<String> combo_mode_payment;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel gst;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_bank_name;
    private javax.swing.JLabel lbl_check_no;
    private javax.swing.JLabel lbl_gst;
    private javax.swing.JLabel lbl_upid;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_bank_name;
    private javax.swing.JTextField txt_cgst;
    private javax.swing.JTextField txt_check_no;
    private javax.swing.JTextField txt_head;
    private javax.swing.JTextArea txt_note;
    private javax.swing.JTextField txt_receiver_name;
    private javax.swing.JTextField txt_reciept_no;
    private javax.swing.JTextField txt_sgst;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_total_in_word;
    private javax.swing.JTextField txt_upid;
    // End of variables declaration//GEN-END:variables
}
