/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.signuppage;

/**
 *
 * @author vsabale
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_allrecord = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        lbl_viewcourse = new javax.swing.JLabel();
        lbl_addmision1 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(153, 255, 102));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setText("Addmision");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("HOME PAGE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        lbl_allrecord.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbl_allrecord.setText("  ALL RECORD");
        lbl_allrecord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        lbl_allrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_allrecordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_allrecordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_allrecordMouseReleased(evt);
            }
        });
        lbl_allrecord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl_allrecordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl_allrecordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lbl_allrecordKeyTyped(evt);
            }
        });
        getContentPane().add(lbl_allrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 100, 28));

        lbllogout.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbllogout.setText("   LOGOUT");
        lbllogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbllogoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbllogoutMouseReleased(evt);
            }
        });
        lbllogout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbllogoutKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lbllogoutKeyTyped(evt);
            }
        });
        getContentPane().add(lbllogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 110, 28));

        lbl_viewcourse.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbl_viewcourse.setText("   VIEW COURSE");
        lbl_viewcourse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        lbl_viewcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewcourseMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_viewcourseMousePressed(evt);
            }
        });
        lbl_viewcourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl_viewcourseKeyPressed(evt);
            }
        });
        getContentPane().add(lbl_viewcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 110, 28));

        lbl_addmision1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lbl_addmision1.setText("  Addmision");
        lbl_addmision1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        lbl_addmision1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addmision1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_addmision1MousePressed(evt);
            }
        });
        lbl_addmision1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl_addmision1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lbl_addmision1KeyTyped(evt);
            }
        });
        getContentPane().add(lbl_addmision1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 100, 28));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_allrecordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_allrecordKeyPressed
 allrecord allrecord = new allrecord();
            allrecord.setVisible(true);           
   

        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_allrecordKeyPressed

    private void lbl_allrecordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_allrecordKeyReleased
      // TODO add your handling code here:
    }//GEN-LAST:event_lbl_allrecordKeyReleased

    private void lbl_allrecordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_allrecordKeyTyped
      // TODO add your handling code here:
    }//GEN-LAST:event_lbl_allrecordKeyTyped

    private void lbl_allrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_allrecordMouseClicked
 allrecord allrecord = new allrecord();
            allrecord.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_lbl_allrecordMouseClicked

    private void lbl_allrecordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_allrecordMousePressed
        // TODO add your handling code here:
         allrecord allrecord = new allrecord();
            allrecord.setVisible(true);
    }//GEN-LAST:event_lbl_allrecordMousePressed

    private void lbl_allrecordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_allrecordMouseReleased
       // TODO add your handling code here:
    }//GEN-LAST:event_lbl_allrecordMouseReleased

    private void lbllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseClicked
SignUp SP=new SignUp();
        SP.setVisible(true);
               // TODO add your handling code here:
    }//GEN-LAST:event_lbllogoutMouseClicked

    private void lbllogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMousePressed
SignUp SP=new SignUp();
        SP.setVisible(true);
               // TODO add your handling code here:
    }//GEN-LAST:event_lbllogoutMousePressed

    private void lbllogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseReleased
SignUp SP=new SignUp();
        SP.setVisible(true);
              // TODO add your handling code here:
    }//GEN-LAST:event_lbllogoutMouseReleased

    private void lbllogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbllogoutKeyPressed
SignUp SP=new SignUp();
        SP.setVisible(true);
              // TODO add your handling code here:
    }//GEN-LAST:event_lbllogoutKeyPressed

    private void lbllogoutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbllogoutKeyTyped
SignUp SP=new SignUp();
        SP.setVisible(true);
              // TODO add your handling code here:
    }//GEN-LAST:event_lbllogoutKeyTyped

    private void lbl_viewcourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewcourseMouseClicked

        coursedetails cd=new coursedetails();
        cd.setVisible(true);
       
    
    }//GEN-LAST:event_lbl_viewcourseMouseClicked

    private void lbl_viewcourseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewcourseMousePressed

        coursedetails cd=new coursedetails();
        cd.setVisible(true);
    
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_viewcourseMousePressed

    private void lbl_viewcourseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_viewcourseKeyPressed

        coursedetails cd=new coursedetails();
        cd.setVisible(true);
     
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_viewcourseKeyPressed

    private void lbl_addmision1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addmision1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addmision1MouseClicked

    private void lbl_addmision1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addmision1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addmision1MousePressed

    private void lbl_addmision1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_addmision1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addmision1KeyPressed

    private void lbl_addmision1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_addmision1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addmision1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_addmision1;
    private javax.swing.JLabel lbl_allrecord;
    private javax.swing.JLabel lbl_viewcourse;
    private javax.swing.JLabel lbllogout;
    // End of variables declaration//GEN-END:variables
}
